apiVersion: v1
kind: BuildConfig
metadata:
  name: php-test
spec:
  triggers: []
  source:
    type: Git
    git:
      uri: 'https://github.com/brandon-sturgeon/ose-examples.git'
    contextDir: php-test/src
    secrets: null
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'php:latest'
  output:
    to:
      kind: ImageStreamTag
      name: 'php-test:latest'
  resources: {  }
  postCommit: {  }
status:
  lastVersion: 1
