apiVersion: v1
kind: DeploymentConfig
metadata:
  name: php-test
  namespace: sample-project
  labels:
    deploymentconfig: php-test
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {  }
  replicas: 1
  test: false
  selector:
    deploymentconfig: php-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: php-test
    spec:
      containers:
        -
          name: php-test
          image: '172.30.2.149:5000/sample-project/php-test:latest'
          ports:
            -
              name: 8080-tcp
              containerPort: 8080
              protocol: TCP
          resources: {  }
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {  }
